<?php

namespace app\utiles;

use Ds\Set;
use Exception;

class ProcesadorPalabras
{
    public static $STOP_WORDS = [
        "a" => 1,
        "actualmente" => 1,
        "adelante" => 1,
        "además" => 1,
        "afirmó" => 1,
        "agregó" => 1,
        "ahora" => 1,
        "ahí" => 1,
        "al" => 1,
        "algo" => 1,
        "alguna" => 1,
        "algunas" => 1,
        "alguno" => 1,
        "algunos" => 1,
        "algún" => 1,
        "alrededor" => 1,
        "ambos" => 1,
        "ampleamos" => 1,
        "ante" => 1,
        "anterior" => 1,
        "antes" => 1,
        "apenas" => 1,
        "aproximadamente" => 1,
        "aquel" => 1,
        "aquellas" => 1,
        "aquellos" => 1,
        "aqui" => 1,
        "aquí" => 1,
        "arriba" => 1,
        "aseguró" => 1,
        "así" => 1,
        "atras" => 1,
        "aunque" => 1,
        "ayer" => 1,
        "añadió" => 1,
        "aún" => 1,
        "bajo" => 1,
        "bastante" => 1,
        "bien" => 1,
        "buen" => 1,
        "buena" => 1,
        "buenas" => 1,
        "bueno" => 1,
        "buenos" => 1,
        "cada" => 1,
        "casi" => 1,
        "cerca" => 1,
        "cierta" => 1,
        "ciertas" => 1,
        "cierto" => 1,
        "ciertos" => 1,
        "cinco" => 1,
        "comentó" => 1,
        "como" => 1,
        "con" => 1,
        "conocer" => 1,
        "conseguimos" => 1,
        "conseguir" => 1,
        "considera" => 1,
        "consideró" => 1,
        "consigo" => 1,
        "consigue" => 1,
        "consiguen" => 1,
        "consigues" => 1,
        "contra" => 1,
        "cosas" => 1,
        "creo" => 1,
        "cual" => 1,
        "cuales" => 1,
        "cualquier" => 1,
        "cuando" => 1,
        "cuanto" => 1,
        "cuatro" => 1,
        "cuenta" => 1,
        "cómo" => 1,
        "da" => 1,
        "dado" => 1,
        "dan" => 1,
        "dar" => 1,
        "de" => 1,
        "debe" => 1,
        "deben" => 1,
        "debido" => 1,
        "decir" => 1,
        "dejó" => 1,
        "del" => 1,
        "demás" => 1,
        "dentro" => 1,
        "desde" => 1,
        "después" => 1,
        "dice" => 1,
        "dicen" => 1,
        "dicho" => 1,
        "dieron" => 1,
        "diferente" => 1,
        "diferentes" => 1,
        "dijeron" => 1,
        "dijo" => 1,
        "dio" => 1,
        "donde" => 1,
        "dos" => 1,
        "durante" => 1,
        "e" => 1,
        "ejemplo" => 1,
        "el" => 1,
        "ella" => 1,
        "ellas" => 1,
        "ello" => 1,
        "ellos" => 1,
        "embargo" => 1,
        "empleais" => 1,
        "emplean" => 1,
        "emplear" => 1,
        "empleas" => 1,
        "empleo" => 1,
        "en" => 1,
        "encima" => 1,
        "encuentra" => 1,
        "entonces" => 1,
        "entre" => 1,
        "era" => 1,
        "erais" => 1,
        "eramos" => 1,
        "eran" => 1,
        "eras" => 1,
        "eres" => 1,
        "es" => 1,
        "esa" => 1,
        "esas" => 1,
        "ese" => 1,
        "eso" => 1,
        "esos" => 1,
        "esta" => 1,
        "estaba" => 1,
        "estabais" => 1,
        "estaban" => 1,
        "estabas" => 1,
        "estad" => 1,
        "estada" => 1,
        "estadas" => 1,
        "estado" => 1,
        "estados" => 1,
        "estais" => 1,
        "estamos" => 1,
        "estan" => 1,
        "estando" => 1,
        "estar" => 1,
        "estaremos" => 1,
        "estará" => 1,
        "estarán" => 1,
        "estarás" => 1,
        "estaré" => 1,
        "estaréis" => 1,
        "estaría" => 1,
        "estaríais" => 1,
        "estaríamos" => 1,
        "estarían" => 1,
        "estarías" => 1,
        "estas" => 1,
        "este" => 1,
        "estemos" => 1,
        "esto" => 1,
        "estos" => 1,
        "estoy" => 1,
        "estuve" => 1,
        "estuviera" => 1,
        "estuvierais" => 1,
        "estuvieran" => 1,
        "estuvieras" => 1,
        "estuvieron" => 1,
        "estuviese" => 1,
        "estuvieseis" => 1,
        "estuviesen" => 1,
        "estuvieses" => 1,
        "estuvimos" => 1,
        "estuviste" => 1,
        "estuvisteis" => 1,
        "estuviéramos" => 1,
        "estuviésemos" => 1,
        "estuvo" => 1,
        "está" => 1,
        "estábamos" => 1,
        "estáis" => 1,
        "están" => 1,
        "estás" => 1,
        "esté" => 1,
        "estéis" => 1,
        "estén" => 1,
        "estés" => 1,
        "ex" => 1,
        "existe" => 1,
        "existen" => 1,
        "explicó" => 1,
        "expresó" => 1,
        "fin" => 1,
        "fue" => 1,
        "fuera" => 1,
        "fuerais" => 1,
        "fueran" => 1,
        "fueras" => 1,
        "fueron" => 1,
        "fuese" => 1,
        "fueseis" => 1,
        "fuesen" => 1,
        "fueses" => 1,
        "fui" => 1,
        "fuimos" => 1,
        "fuiste" => 1,
        "fuisteis" => 1,
        "fuéramos" => 1,
        "fuésemos" => 1,
        "gran" => 1,
        "grandes" => 1,
        "gueno" => 1,
        "ha" => 1,
        "haber" => 1,
        "habida" => 1,
        "habidas" => 1,
        "habido" => 1,
        "habidos" => 1,
        "habiendo" => 1,
        "habremos" => 1,
        "habrá" => 1,
        "habrán" => 1,
        "habrás" => 1,
        "habré" => 1,
        "habréis" => 1,
        "habría" => 1,
        "habríais" => 1,
        "habríamos" => 1,
        "habrían" => 1,
        "habrías" => 1,
        "habéis" => 1,
        "había" => 1,
        "habíais" => 1,
        "habíamos" => 1,
        "habían" => 1,
        "habías" => 1,
        "hace" => 1,
        "haceis" => 1,
        "hacemos" => 1,
        "hacen" => 1,
        "hacer" => 1,
        "hacerlo" => 1,
        "haces" => 1,
        "hacia" => 1,
        "haciendo" => 1,
        "hago" => 1,
        "han" => 1,
        "has" => 1,
        "hasta" => 1,
        "hay" => 1,
        "haya" => 1,
        "hayamos" => 1,
        "hayan" => 1,
        "hayas" => 1,
        "hayáis" => 1,
        "he" => 1,
        "hecho" => 1,
        "hemos" => 1,
        "hicieron" => 1,
        "hizo" => 1,
        "hoy" => 1,
        "hube" => 1,
        "hubiera" => 1,
        "hubierais" => 1,
        "hubieran" => 1,
        "hubieras" => 1,
        "hubieron" => 1,
        "hubiese" => 1,
        "hubieseis" => 1,
        "hubiesen" => 1,
        "hubieses" => 1,
        "hubimos" => 1,
        "hubiste" => 1,
        "hubisteis" => 1,
        "hubiéramos" => 1,
        "hubiésemos" => 1,
        "hubo" => 1,
        "igual" => 1,
        "incluso" => 1,
        "indicó" => 1,
        "informó" => 1,
        "intenta" => 1,
        "intentais" => 1,
        "intentamos" => 1,
        "intentan" => 1,
        "intentar" => 1,
        "intentas" => 1,
        "intento" => 1,
        "ir" => 1,
        "junto" => 1,
        "la" => 1,
        "lado" => 1,
        "largo" => 1,
        "las" => 1,
        "le" => 1,
        "les" => 1,
        "llegó" => 1,
        "lleva" => 1,
        "llevar" => 1,
        "lo" => 1,
        "los" => 1,
        "luego" => 1,
        "lugar" => 1,
        "manera" => 1,
        "manifestó" => 1,
        "mayor" => 1,
        "me" => 1,
        "mediante" => 1,
        "mejor" => 1,
        "mencionó" => 1,
        "menos" => 1,
        "mi" => 1,
        "mientras" => 1,
        "mio" => 1,
        "mis" => 1,
        "misma" => 1,
        "mismas" => 1,
        "mismo" => 1,
        "mismos" => 1,
        "modo" => 1,
        "momento" => 1,
        "mucha" => 1,
        "muchas" => 1,
        "mucho" => 1,
        "muchos" => 1,
        "muy" => 1,
        "más" => 1,
        "mí" => 1,
        "mía" => 1,
        "mías" => 1,
        "mío" => 1,
        "míos" => 1,
        "nada" => 1,
        "nadie" => 1,
        "ni" => 1,
        "ninguna" => 1,
        "ningunas" => 1,
        "ninguno" => 1,
        "ningunos" => 1,
        "ningún" => 1,
        "no" => 1,
        "nos" => 1,
        "nosotras" => 1,
        "nosotros" => 1,
        "nuestra" => 1,
        "nuestras" => 1,
        "nuestro" => 1,
        "nuestros" => 1,
        "nueva" => 1,
        "nuevas" => 1,
        "nuevo" => 1,
        "nuevos" => 1,
        "nunca" => 1,
        "o" => 1,
        "ocho" => 1,
        "os" => 1,
        "otra" => 1,
        "otras" => 1,
        "otro" => 1,
        "otros" => 1,
        "para" => 1,
        "parece" => 1,
        "parte" => 1,
        "partir" => 1,
        "pasada" => 1,
        "pasado" => 1,
        "pero" => 1,
        "pesar" => 1,
        "poca" => 1,
        "pocas" => 1,
        "poco" => 1,
        "pocos" => 1,
        "podeis" => 1,
        "podemos" => 1,
        "poder" => 1,
        "podria" => 1,
        "podriais" => 1,
        "podriamos" => 1,
        "podrian" => 1,
        "podrias" => 1,
        "podrá" => 1,
        "podrán" => 1,
        "podría" => 1,
        "podrían" => 1,
        "poner" => 1,
        "por" => 1,
        "por qué" => 1,
        "porque" => 1,
        "posible" => 1,
        "primer" => 1,
        "primera" => 1,
        "primero" => 1,
        "primeros" => 1,
        "principalmente" => 1,
        "propia" => 1,
        "propias" => 1,
        "propio" => 1,
        "propios" => 1,
        "próximo" => 1,
        "próximos" => 1,
        "pudo" => 1,
        "pueda" => 1,
        "puede" => 1,
        "pueden" => 1,
        "puedo" => 1,
        "pues" => 1,
        "que" => 1,
        "quedó" => 1,
        "queremos" => 1,
        "quien" => 1,
        "quienes" => 1,
        "quiere" => 1,
        "quién" => 1,
        "qué" => 1,
        "realizado" => 1,
        "realizar" => 1,
        "realizó" => 1,
        "respecto" => 1,
        "sabe" => 1,
        "sabeis" => 1,
        "sabemos" => 1,
        "saben" => 1,
        "saber" => 1,
        "sabes" => 1,
        "se" => 1,
        "sea" => 1,
        "seamos" => 1,
        "sean" => 1,
        "seas" => 1,
        "segunda" => 1,
        "segundo" => 1,
        "según" => 1,
        "seis" => 1,
        "ser" => 1,
        "seremos" => 1,
        "será" => 1,
        "serán" => 1,
        "serás" => 1,
        "seré" => 1,
        "seréis" => 1,
        "sería" => 1,
        "seríais" => 1,
        "seríamos" => 1,
        "serían" => 1,
        "serías" => 1,
        "seáis" => 1,
        "señaló" => 1,
        "si" => 1,
        "sido" => 1,
        "siempre" => 1,
        "siendo" => 1,
        "siete" => 1,
        "sigue" => 1,
        "siguiente" => 1,
        "sin" => 1,
        "sino" => 1,
        "sobre" => 1,
        "sois" => 1,
        "sola" => 1,
        "solamente" => 1,
        "solas" => 1,
        "solo" => 1,
        "solos" => 1,
        "somos" => 1,
        "son" => 1,
        "soy" => 1,
        "su" => 1,
        "sus" => 1,
        "suya" => 1,
        "suyas" => 1,
        "suyo" => 1,
        "suyos" => 1,
        "sí" => 1,
        "sólo" => 1,
        "tal" => 1,
        "también" => 1,
        "tampoco" => 1,
        "tan" => 1,
        "tanto" => 1,
        "te" => 1,
        "tendremos" => 1,
        "tendrá" => 1,
        "tendrán" => 1,
        "tendrás" => 1,
        "tendré" => 1,
        "tendréis" => 1,
        "tendría" => 1,
        "tendríais" => 1,
        "tendríamos" => 1,
        "tendrían" => 1,
        "tendrías" => 1,
        "tened" => 1,
        "teneis" => 1,
        "tenemos" => 1,
        "tener" => 1,
        "tenga" => 1,
        "tengamos" => 1,
        "tengan" => 1,
        "tengas" => 1,
        "tengo" => 1,
        "tengáis" => 1,
        "tenida" => 1,
        "tenidas" => 1,
        "tenido" => 1,
        "tenidos" => 1,
        "teniendo" => 1,
        "tenéis" => 1,
        "tenía" => 1,
        "teníais" => 1,
        "teníamos" => 1,
        "tenían" => 1,
        "tenías" => 1,
        "tercera" => 1,
        "ti" => 1,
        "tiempo" => 1,
        "tiene" => 1,
        "tienen" => 1,
        "tienes" => 1,
        "toda" => 1,
        "todas" => 1,
        "todavía" => 1,
        "todo" => 1,
        "todos" => 1,
        "total" => 1,
        "trabaja" => 1,
        "trabajais" => 1,
        "trabajamos" => 1,
        "trabajan" => 1,
        "trabajar" => 1,
        "trabajas" => 1,
        "trabajo" => 1,
        "tras" => 1,
        "trata" => 1,
        "través" => 1,
        "tres" => 1,
        "tu" => 1,
        "tus" => 1,
        "tuve" => 1,
        "tuviera" => 1,
        "tuvierais" => 1,
        "tuvieran" => 1,
        "tuvieras" => 1,
        "tuvieron" => 1,
        "tuviese" => 1,
        "tuvieseis" => 1,
        "tuviesen" => 1,
        "tuvieses" => 1,
        "tuvimos" => 1,
        "tuviste" => 1,
        "tuvisteis" => 1,
        "tuviéramos" => 1,
        "tuviésemos" => 1,
        "tuvo" => 1,
        "tuya" => 1,
        "tuyas" => 1,
        "tuyo" => 1,
        "tuyos" => 1,
        "tú" => 1,
        "ultimo" => 1,
        "un" => 1,
        "una" => 1,
        "unas" => 1,
        "uno" => 1,
        "unos" => 1,
        "usa" => 1,
        "usais" => 1,
        "usamos" => 1,
        "usan" => 1,
        "usar" => 1,
        "usas" => 1,
        "uso" => 1,
        "usted" => 1,
        "va" => 1,
        "vais" => 1,
        "valor" => 1,
        "vamos" => 1,
        "van" => 1,
        "varias" => 1,
        "varios" => 1,
        "vaya" => 1,
        "veces" => 1,
        "ver" => 1,
        "verdad" => 1,
        "verdadera" => 1,
        "verdadero" => 1,
        "vez" => 1,
        "vosotras" => 1,
        "vosotros" => 1,
        "voy" => 1,
        "vuestra" => 1,
        "vuestras" => 1,
        "vuestro" => 1,
        "vuestros" => 1,
        "y" => 1,
        "ya" => 1,
        "yo" => 1,
        "él" => 1,
        "éramos" => 1,
        "ésta" => 1,
        "éstas" => 1,
        "éste" => 1,
        "éstos" => 1,
        "última" => 1,
        "últimas" => 1,
        "último" => 1,
        "últimos"=> 1
    ];



    /**
     * @return string
     */
    public static function removeStopWords($texto)
    {
        $STOP_WORDS = &self::$STOP_WORDS;
        //separaremos el texto en un arreglo de palabras con formato [0-9a-zA-Z_-'] (preservando el orden)
        $words = preg_split('/[^\w|á|é|í|ó|ú|Á|É|Í|Ó|Ú|ñ|Ñ\']+/', $texto, -1, PREG_SPLIT_NO_EMPTY);

        if(count($words) > 1)
        {
            $words = array_filter($words, function ($w) use (&$STOP_WORDS) {
                return !isset($STOP_WORDS[strtolower($w)]);
                # if utf-8: mb_strtolower($w, "utf-8")
                }
            );
        }

        if(!empty($words))
            return implode(" ", $words);
        return $texto;
        
    }

    /**
     * Elimina hasta la aparición del primer salto de línea (incluído)
     * @return string
     */
    public static function stripFirstLine($texto) {        
        return substr($texto, strpos($texto, "\n") + 1);
    }

    public static function removeFirstLineAndStopWords($texto){
        return self::removeStopWords(self::stripFirstLine($texto));
    }


    /**
     * Retorna un arreglo con la cantidad de veces que aparece cada palabra
     * Si se le envía un arreglo del mismo tipo (diccionario) en $array_to_merge
     * retornará el total de palabeas agregado.
     * @return string[]
     */
    public static function ArrayMapCantidadPalabras($texto, $array_to_merge = null, $sort = false)
    {
        $palabras = [];
        foreach(explode(' ', $texto) as $palabra)
        {
            if(!is_numeric($palabra))
            {
                if(!isset($palabras[strtolower($palabra)]))
                {
                    $palabras[strtolower($palabra)] = 1;
                }
                else
                {
                    $palabras[strtolower($palabra)] += 1;
                }
            } 
        }
        
        
        if(!is_null($array_to_merge)){
            foreach($array_to_merge as $key => $value)
            {
                if(!isset($palabras[$key]))
                {
                    $palabras[$key] = $value;
                }
                else
                {
                    $palabras[$key] += $value;
                }
            }
        }

        if($sort)
        {
            array_multisort($palabras, SORT_DESC, $palabras);
            //usort($palabras, function($a, $b){return $a > $b;}); //esto olvida las keys
        }
        
        return $palabras;
    }
}